server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  config:
    import: configserver:http://localhost:9296

  cloud:
    gateway:
      routes:
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE   #lb load balancer in order service
          predicates:
            - Path=/order/**
        - id : PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE   #lb load balancer
          predicates:
            - Path=/product/**
        - id : PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE   #lb load balancer
          predicates:
            - Path=/payment/**
